services:
  - type: web
    name: baocao-ckds
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 60
    healthCheckPath: /health
    envVars:
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: TENANT_ID
        sync: false
      - key: SITE_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
